const FALL_BACK_IMAGE = '/images/default-tech-blog-cover.png';
const BLUR_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAMAAAC6sdbXAAAAJ1BMVEX///8AAADMzMxycnKhoaHY2Ni/v7/z8/PDw8OYmJg3Nzenp6fj4+PZr2xPAAAAAXRSTlMAQObYZgAAAC1JREFUGJVjYGBgYGRgZGJmYGBgZmBlZGZgYGJkYGCQAAAwxgYkJgYADzUGAQAzBY8k1v6dMAAAAASUVORK5CYII=';

export { FALL_BACK_IMAGE, BLUR_DATA_URL };
